GET {{base_url}}/spiders
Accept: application/json
Authorization: {{token}}

###

POST {{base_url}}/spiders
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: {{token}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.zip"

< ../test.zip
--WebAppBoundary
Content-Disposition: form-data; name="name"

{{spider_name}}
--WebAppBoundary--

> {% client.global.set("spider_id", response.body.data.id); %}

###

DELETE {{base_url}}/spiders/{{spider_id}}
Accept: application/json
Authorization: {{token}}

###

GET {{base_url}}/spiders/{{spider_id}}/versions
Accept: application/json
Authorization: {{token}}

###

POST {{base_url}}/spiders/{{spider_id}}/versions
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: {{token}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.zip"

< ../test.zip
--WebAppBoundary
Content-Disposition: form-data; name="name"

{{spider_id}}
--WebAppBoundary--

> {% client.global.set("spider_version_id", response.body.data.id); %}

###

DELETE {{base_url}}/spiders/{{spider_id}}/versions/{{spider_version_id}}
Accept: application/json
Authorization: {{token}}

###
