GET {{base_url}}/tasks
Accept: application/json
Authorization: {{token}}

###

POST {{base_url}}/tasks
Content-Type: application/json
Authorization: {{token}}

{
  "spider_id": "{{spider_id}}",
  "cmd": "sh run.sh"
}

> {% client.global.set("task_id", response.body.data.id); %}

###

GET {{base_url}}/tasks/{{task_id}}
Accept: application/json
Authorization: {{token}}

###

POST {{base_url}}/tasks/{{task_id}}/cancel
Accept: application/json
Authorization: {{token}}

###
